export * from "./Home";
export * from "./Intranet";
export * from "./Login";
export * from "./PaginaNoEncontrada";
export * from "./Registro";
export * from "./Eventos";
export * from "./Publicaciones";
export * from "./Aventuras";
export * from "./Ampay";
export * from "./TiendaProducto";
//para gestionar el commercio 
export * from "./eCommerce";